version: '2'
services:
 mysql:
  build: ./mysql-app/
  container_name: mysql_server
  expose:
  - "3306"
  ports:
  - "3306:3306"
  env_file:
  - ./env_vars
 tomcat:
  build: ./tomcat-app/
  container_name: tomcat_server
  expose:
  - "8080"
  ports:
   - "8080:8080"
  depends_on:
   - mysql
  links:
    - mysql
  volumes:
    - /tmp/war/:/usr/local/tomcat/webapps/